version: 0.2
    
phases:
  #install:
  #  runtime-versions:
  #    nodejs: latest
  #  commands:
  #    - echo Installing app dependencies...
  #    - echo Run "yarn install"...
  #    - yarn install
      
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=111782135825.dkr.ecr.us-east-2.amazonaws.com/vehicle-repository
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Entered the build phase...
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
