version: 0.2
    
phases:
  #install:
  #  runtime-versions:
  #    nodejs: latest
  #  commands:
  #    - echo Installing app dependencies...
  #    - echo Run "yarn install"...
  #    - yarn install
      
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Building the Docker image...
      - docker build -t vehicle-query:latest .
      - docker tag vehicle-query:latest vehicle-query:latest
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Pushing the Docker image...
